name: Test React app
on: [workflow_dispatch]
jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install --production
  run-tests:
    runs-on: ubuntu-latest
    needs: set-up
    steps:
      - run: npm run test